UNFPAInnovation/GetIN-Web-2.0

public/index.html, src/App.js, src/api/services.js, src/components/SideNav.js, src/pages/AncVisits.js, src/pages/FollowUps.js, src/styles/Login.scss
- To view follow ups and girls details in the dashboard
Follow up page route in App.js, FollowUps.js component was created, new data
formters introduced i.e (Date, Yes or No, Age)
=> Feat: Follow up page with http requests from the back end

src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/components/DeliveriesCard/index.js
- Deliveries card component showing number of deliveries with in
a time period.
- Does not currently calculate the increase / decrease from previous
time period.
resolves #GETIN-21 #GETIN-25 #10
=> Feature: Dashboard - Deliveries card

src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/components/FollowUpsCard/index.js
- Deliveries card component showing number of deliveries with in
a time period.
- Does not currently calculate the increase / decrease from previous
time period.
resolves #GETIN-21 #GETIN-26 #10
=> Feature: Dashboard - Follow ups card

src/components/Layout.js, src/pages/Dashboard/Dashboard.js, src/styles/global.scss
- Logic to show spinner to show when data is loading.
- Corresponding CSS rules for the spinner
resolves: #10
=> Feature: Dashboard - Loading data component

src/pages/Dashboard/Dashboard.js, src/utils/getData.js
- Activated data filters for the dashboard. You can now filter and
get data for specific periods.
- New endpoint for mapping_encounters.
- Appended filters to urls.
resolves #10
=> Feature: Dashboard - Data filters and new endpoints

src/components/Charts/AgeGroupOfMappedGirlsBarChart.js, src/components/Charts/chartOptions.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/components/AgeGroupOfMappedGirlsBarChart/index.js, src/pages/Dashboard/components/MappedGirlsCard/index.js, src/utils/getData.js
- New component AgeGroupOfMappedGirlsBarChartCard to display Chart
- New Chart AgeGroupOfMappedGirlsBarChart
- New mappingEncountersStats endpoint for dashboard data
resolves: #GETIN-27 #10
=> Feature: Dashboard - Age Group of Mapped Girls Bar Chart

src/components/Charts/chartOptions.js
- Removed grid lines from x axis
=> Feature: Dashboard - Chart options

src/components/Layout.js
- Resized the app layout
- Side bar now 2
- Main content area now 10
=> Layout: Resizing.

src/components/ChartCard.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/components/AgeGroupOfMappedGirlsBarChart/index.js, src/styles/global.scss
- New Chart card compoent with coresponding CSS
=> Feature: Dashboard - Chart Card component

src/pages/Dashboard/components/DeliveriesCard/index.js
- Rename deliveries card from "Deliveries" to "Health facility Deliveries"
resolves: GETIN-25, #10
=> Fix: Rename Deliveries card

src/components/Charts/MappedGirlsPerSubcountyBarChart.js, src/components/Charts/utils/utils.js, src/pages/Dashboard/components/MappedGirlsPerSubcountyBarChart/index.js
- Introduced high Charts
- Rewriten chart in highcharts format
- Introduced utility functions to manipulate data in correct format.
=> Feature: Mapped Girls per subcounty chart.

src/pages/MappedGirls.js
- Shows column for date girl mapped
closes #34
=> Show date for mapped girls

src/App.js, src/api/services.js, src/components/SideNav.js, src/pages/Deliveries.js, src/pages/Login.js
- To view Deliveries of girls in the dashboard
Deliveries page route, in App.js, Deliveries Service, Deliveries Component created, new data
formeters, i.e (deliveries, family planning), login, variable updated
=> Feature: Deliveries page with requests from the backend

src/pages/HealthFacilities.js, src/pages/MappedGirls.js
**What does the PR do**
The PR adds the health_facility level data in the column Level under Health Facilities
**What task is completed by the PR**
Populating of the level column under Health Facilities
**How to manually test**
Run a `git checkout ` to the branch `healthFacilities` then run `yarn start` for the application to open.
Then visit the Health Facilities from the same Nav to see the functionality.
=> ft(healthFacilities): add health_facility data

package.json, src/pages/HealthFacilities.js, yarn.lock
**What does this PR do?**
Populates the level field with data
**Description of the task to be completed.**
Add facility level to the health facilities field in the dashboard
**How should this be manually tested?**
Checkout to the **ft-healthfacilities-level** branch
Pull the changes
Run the server and refresh the dashboard
**Any background context you want to provide?**
None
**What are the relevant stories?**
No data has been captured under health facilities, it's an empty feature
**Screenshots(if appropriate)**
None
**Questions**
None
=> Ft healthfacilities level

package.json, src/pages/HealthFacilities.js, yarn.lock
**What does this PR do?**
Populates the sub-county field with data
**Description of the task to be completed.**
Add sub-county name to the health facilities field in the dashboard
**How should this be manually tested?**
Checkout to the **ft-healthfacilities-subcounty-name** branch
Pull the changes
Run the server and refresh the dashboard
**Any background context you want to provide?**
None
**What are the relevant stories?**
No data has been captured under health facilities, it's an empty feature
**Screenshots(if appropriate)**
None
**Questions**
None
=> Ft healthfacilities subcounty name

src/pages/Deliveries/HealthFacility.js, src/pages/HealthFacilities.js
**What does the PR do**
The PR checks if the data returned from row.family_planning is an empty array and return nothing.
**what task is the PR solving**
The crashing of Deliveries when accessed
=> Deliveries

src/pages/Deliveries/HealthFacility.js, src/pages/Deliveries/Home.js
**What does the PR do**
Checks for undefined of some values
**What task is the PR solving**
Crashing of the deliveries section
=> checking for undefined value

src/pages/HealthFacilities.js
**What does this PR do?**
Adds average deliveries to the Healthfacilities field
**Description of the task to be completed.**
The Getin average deliveries colum should be filled with data
**How should this be manually tested?**
- Pull the changes 
- Run `git checkout ft-healthfacilities-add-average_deliveries` 
- Run the server on localhost and visit this endpoint http://localhost:3000/health_facilities
**Any background context you want to provide?**
None
**What are the relevant stories?**
No data captured under Healthfacilities
**Screenshots(if appropriate)**
None
**Questions**
None
=> ft(Healthfacilities):Add average_deliveries

src/pages/MappedGirls.js, yarn.lock
**What does the PR do?**
The PR removes the unused column in the manage column under mapped girls.
=> removed voucher card

src/pages/Settings/Add/HealthFacility.js, src/pages/Settings/HealthFacilities.js, src/pages/Settings/index.js
- Create UI for adding new health facility
partly solves: https://outboxhub.atlassian.net/browse/GDU-18
=> Feature: Provide ability for the admin to add health facilities.

src/App.js, src/api/services.js, src/components/Header.js, src/components/SideNav.js, src/context/AppReducer.js, src/context/GlobalState.js, src/styles/global.scss
- Add the UI for the District Filter
- Create global state to manage to effect data updates by filter
Solves part of: https://outboxhub.atlassian.net/browse/GDU-13
=> Feature: Provide ability for the admin to filter by districts.

src/App.js, src/api/index.js, src/api/services.js, src/components/Charts/FamilyPlaning.js, src/components/Charts/MappedGirlsBySubCounty.js, src/pages/Dashboard/Dashboard.js, src/pages/Deliveries/HealthFacility.js, src/pages/Deliveries/Home.js, src/pages/FollowUps.js, src/pages/HealthFacilities.js, src/pages/Login.js, src/pages/MappedGirls.js, src/pages/Settings/Add/HealthFacility.js, src/pages/Settings/HealthFacilities.js, src/pages/Settings/Users/Admin.js, src/pages/Settings/Users/GetIN/Ambulance.js, src/pages/Settings/Users/GetIN/Midwife.js, src/pages/Settings/Users/GetIN/VHT.js, src/pages/Settings/index.js, src/pages/Users/Midwife.js, src/pages/Users/Users.js, src/pages/Users/VHT.js, src/utils/index.js
- removed console.log statements
- resolved errors indicated by eslint
- remove some table columns on default view
- enable sync of data for district in the settings tab for GetIn Users
- remove Kampala,Bundibugjo and Arua from district list
- Remove Parish and village fields from add health facility form
=> Fix: clean up codebase to align with eslint, update user views

src/api/services.js, src/pages/ANC/Attended.js, src/pages/ANC/Completed.js, src/pages/ANC/Expected.js, src/pages/ANC/Missed.js, src/pages/Deliveries/HealthFacility.js, src/pages/Deliveries/Home.js, src/pages/FollowUps.js, src/pages/HealthFacilities.js, src/pages/MappedGirls.js, src/pages/Settings/Add/HealthFacility.js, src/pages/Settings/HealthFacilities.js, src/pages/Users/Ambulance.js, src/pages/Users/Midwife.js, src/pages/Users/VHT.js, src/utils/index.js
- Provide the ability for the admin to view respective districts in the various data tables
Solves:https://outboxhub.atlassian.net/browse/GDU-25
=> Feature: Provide ability for the admin to view

src/pages/MappedGirls.js, src/pages/Settings/Users/GetIN/Add/Midwife.js, src/pages/Settings/Users/GetIN/Update/Midwife.js, src/utils/index.js
- Changed default date of date filters to from start of year
- Splitted VHT details in table when exporting mapped women data
Solves:
- https://outboxhub.atlassian.net/browse/GDU-27
- https://outboxhub.atlassian.net/browse/GDU-26
=> Fix: Update admin UI view

src/api/services.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/components/MappedGirlsPerDistrict/index.js, src/pages/Settings/Users/GetIN/Add/Midwife.js, src/pages/Settings/Users/GetIN/Add/Vht.js
- Graphically represent data of mapped women per district
- Provide the ability to attach a district when creating a User
- https://outboxhub.atlassian.net/browse/GDU-19
- https://outboxhub.atlassian.net/browse/GDU-28
=> Feature: Admin should see a bar graph of mapped women per district on the dashboard

src/pages/ANC/Attended.js
- Add an ability for the admin to view additional services.
Solves: https://outboxhub.atlassian.net/browse/GDU-30
=> Feature: Add an ability for the admin to view additional services.

src/api/services.js, src/components/Header.js, src/pages/ANC/Attended.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/components/MappedGirlsPerDistrict/index.js, src/pages/Dashboard/components/MappedGirlsPerSubcountyBarChart/index.js, src/pages/Login.js, src/pages/Settings/Add/HealthFacility.js, src/pages/Settings/Districts.js, src/pages/Settings/Update/Admin.js, src/pages/Settings/Update/ChangePassword.js, src/pages/Settings/Users/Admin.js, src/pages/Settings/Users/GetIN/Add/Dho.js, src/pages/Settings/Users/GetIN/Add/Vht.js, src/pages/Settings/Users/GetIN/Dho.js, src/pages/Settings/Users/GetIN/Update/Dho.js, src/pages/Settings/Users/GetIN/Update/Midwife.js, src/pages/Settings/Users/GetIN/Update/Vht.js, src/pages/Settings/Users/GetIN/Users.js, src/pages/Settings/index.js
- Adds ability for the Super administrator to add a DHO
- Adds ability for the Super administrator to view DHOs
- Provides ability for the admin and other users to reset passwords
- https://outboxhub.atlassian.net/browse/GDU-33
- https://outboxhub.atlassian.net/browse/GDU-32
- https://outboxhub.atlassian.net/browse/GDU-31
=> Feature: Update Admin Settings and Views

src/pages/Settings/Add/HealthFacility.js, src/pages/Settings/Users/GetIN/Midwife.js, src/pages/Settings/Users/GetIN/VHT.js, src/pages/Users/Midwife.js, src/pages/Users/VHT.js, src/utils/index.js
- Filters out test users(vhts and Midwives) from the data received from the backend
- Changes the format of the health facility level value that's sent to the backend
=> Fix: Filter out test users (vhts and midwives) from data tables.
